/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Exercise: Load 2 values from memory, add them and store the result back to the memory using inline assembly
 * statements. */

int main(void)
{
	__asm volatile("LDR R1,=#0x20001000");	// Loads the immediate value in R1 (it's a 32 bit hexadecimal)
	__asm volatile("LDR R2,=#0x20001004");	// Same as above line but with R2
	__asm volatile("LDR R0,[R1]");			// Load in R0 the value stored in address stored in R1
	__asm volatile("LDR R1,[R2]");			// Load in R1 the value stored in address stored in R2
	__asm volatile("ADD R0,R0,R1");			// Add the values stored in R0 and R1 and stores the result in R0
	__asm volatile("STR R0,[R2]");			// Stores the value of R0 in memory location stored in R2

	int val = 50;

	__asm volatile("MOV R0,%0": :"r"(val));	/* Explanation: "MOV R0,%0" means
	that the contents of variable val are going to be moved to R0, %0 indicates
	that the value to be moved to R0 is the first operand, %1 the second and so
	on. The blank space after the first colon indicates that there is no outputs,
	remember the format of the inline assembly statement
	__asm volatile(code: output operand list: input operand list: clobber list).
	"r"(val) means that the general registers will be used to store the value of
	val, data manipulation in general. */

	int control_reg;
	// Read CONTROL register to control_reg C variable
	__asm volatile("MRS %0,CONTROL":"=r"(control_reg));
	/* "MRS %0,CONTROL" means that the value of the CONTROL register will be
	 * moved to the first operand of output operands, MRS mnemonic is used in
	 * this case because CONTROL is a special register, MRS is for move the
	 * contents of a special register to a general-purpose register.
	 * In "=r"(control_reg) =r means that the output operator is write only. */

	// Example 4: copy the contents of a pointer into another variable.
	int p1, *p2;

	p2 = (int*)0x20000008;

	__asm volatile("LDR %0,[%1]": "=r"(p1): "r"(p2));
    /* Loop forever */
	for(;;);
	/* To put some values in memory locations stored in R1 and R2
	 * go to Window>Show view>Memory then click the plus button */
}
