/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// This function executes in thread mode of the processor.
void generate_interrupt()
{
	uint32_t *pSTIR  = (uint32_t *)0xE000EF00;
	uint32_t *pISERO = (uint32_t *)0xE000E100;

	// Enable IRQ3 interrupt
}

// This function executes in thread mode of the processor.
int main(void)
{
	printf("In thread mode: before interrupt\n");

	generate_interrupt();

	printf("In thread mode: after interrupt\n");
    /* Loop forever */
	for(;;);
}
